backend:
  name: git-gateway
  branch: main # or master, depending on your default branch name

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price (€)", name: "price", widget: "number", value_type: "float"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
